player:
  # 死亡時に失う経験値割合(%)
  # ex)
  #     lv10になるために合計で100必要
  #     lv11になるために合計で150必要
  # lv10で死亡したとき，
  # 失う経験値 = (150 - 100) * (death_penalty / 100)
  death_penalty: 7.0

  # この半径以内のブロック(y軸は無視)はプレイヤーしか破壊できない
  # GameModeがクリエイティブの時は無視
  protect_radius: 8.0

  # この値以上の重力がかかるブロックは破壊できない
  # 例えば，上に4つのブロックがあった場合，重力は4となる
  max_breakable_gravity: 7

  # フォローできる最大人数
  max_follow: 100

elytra:
  # Time it takes to charge up a jump in ticks
  # 1 second = 20 ticks
  # default = 60 ticks = 3 seconds
  chargeup_time: 60

  # Elytra gliding speed multiplier
  # default = 1.0
  speed_multiplier: 1.0

  # Launch strength multiplier
  # default = 1.0
  launch_multiplier: 1.0

world:
  # 正方形の１辺の長さ
  # 実際には±0座標を中心とするので
  # min(x,z) = -(side_length/2),-(side_length/2)
  # max(x,z) = side_length/2,side_length/2
  side_length: 20000.0

# スキル
# マナを用いずに発動可能な能力
skill:
  # 体力回復スキル
  heal:
    # 回復割合 (%)
    ratio: 5.0
    # 発動確率 (%)
    probability: 20.0

  # コンボスキル
  mine_combo:
    # 継続可能時間(秒)
    continuation_seconds: 10.0
    # コンボ減少間隔(秒)
    # 1間隔につきコンボが1割減少する
    decrease_interval: 10.0

  # 瞬間移動スキル
  flash:
    # クールタイム(秒)
    # 整数で指定
    cooltime: 3

  # 一時強化スキル
  mine_burst:
    # 強化時間(秒)
    # 整数で指定
    duration: 7
    # クールタイム(秒)
    # 整数で指定
    cooltime: 30

# スペル
# マナを必ず用いる能力
spell:
  # マナ回復スキル
  stella_clair:
    # 回復割合(%)
    ratio: 7.0
    # 発動確率(%)
    probability: 15.0

  # 範囲破壊スキル
  apostol:
    # 1ブロック当たりのマナ消費量
    mana_per_block: 2.0
    # 幅，高さ，広さの最大値
    # 整数で指定
    limit_size: 5
    # 遅延エフェクトの遅延時間(秒)
    delay: 0.2

# TRUEの時debug.ymlに従う
# データベースの書き込みは行わない
debug_mode: false


